# Generated by Django 3.2.7 on 2021-09-16 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eshopapp', '0002_auto_20210916_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='prenom',
        ),
    ]
