# Generated by Django 3.2.7 on 2021-09-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eshopapp', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adresse',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
